name: ${NAME}
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_ENV: ${APP_ENV}
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SCHEMA: ${DB_SCHEMA}
    depends_on:
      psql:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - open_fermentations
      - devices

  mqtt:
    image: eclipse-mosquitto:alpine
    volumes:
      - ./.mqtt/config:/mosquitto/config
      - ./.mqtt/data:/mosquitto/data
      - ./.mqtt/log:/mosquitto/log
    networks:
      - devices
    ports:
      - ${MQTT_PORT}:${MQTT_PORT}
    stdin_open: true
    tty: true


  psql:
    image: postgres:latest
    restart: unless-stopped
    environment:
      # TODO: add port to environment variables to set the port according to the .env
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - psql_volume:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}'"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - open_fermentations
      - migration_net

  migrate:
    image: migrate/migrate
    depends_on:
      psql:
        condition: service_healthy
    networks:
      - migration_net
    volumes:
      - ./migrations:/migrations
    command: [
      "-path",
      "/migrations/", 
      "-database",
      "${DB_CONNECTION_STRING}",
      "up"
    ]

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - psql
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
    networks:
      - open_fermentations

volumes:
  psql_volume:
  pgadmin_volume:
  mqtt_volume:
networks:
  open_fermentations:
  migration_net:
  devices:
