// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockdevices

import (
	"open-fermentations/internal/devices"

	"github.com/eclipse/paho.mqtt.golang"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMQTT creates a new instance of MockMQTT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMQTT(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMQTT {
	mock := &MockMQTT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMQTT is an autogenerated mock type for the MQTT type
type MockMQTT struct {
	mock.Mock
}

type MockMQTT_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMQTT) EXPECT() *MockMQTT_Expecter {
	return &MockMQTT_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockMQTT
func (_mock *MockMQTT) Publish(topic string, payload *devices.Payload) error {
	ret := _mock.Called(topic, payload)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, *devices.Payload) error); ok {
		r0 = returnFunc(topic, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMQTT_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockMQTT_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - topic string
//   - payload *devices.Payload
func (_e *MockMQTT_Expecter) Publish(topic any, payload any) *MockMQTT_Publish_Call {
	return &MockMQTT_Publish_Call{Call: _e.mock.On("Publish", topic, payload)}
}

func (_c *MockMQTT_Publish_Call) Run(run func(topic string, payload *devices.Payload)) *MockMQTT_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *devices.Payload
		if args[1] != nil {
			arg1 = args[1].(*devices.Payload)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMQTT_Publish_Call) Return(err error) *MockMQTT_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMQTT_Publish_Call) RunAndReturn(run func(topic string, payload *devices.Payload) error) *MockMQTT_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockMQTT
func (_mock *MockMQTT) Subscribe(topic string, qos byte, messageHandler mqtt.MessageHandler) error {
	ret := _mock.Called(topic, qos, messageHandler)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, byte, mqtt.MessageHandler) error); ok {
		r0 = returnFunc(topic, qos, messageHandler)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMQTT_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockMQTT_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - topic string
//   - qos byte
//   - messageHandler mqtt.MessageHandler
func (_e *MockMQTT_Expecter) Subscribe(topic any, qos any, messageHandler any) *MockMQTT_Subscribe_Call {
	return &MockMQTT_Subscribe_Call{Call: _e.mock.On("Subscribe", topic, qos, messageHandler)}
}

func (_c *MockMQTT_Subscribe_Call) Run(run func(topic string, qos byte, messageHandler mqtt.MessageHandler)) *MockMQTT_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 byte
		if args[1] != nil {
			arg1 = args[1].(byte)
		}
		var arg2 mqtt.MessageHandler
		if args[2] != nil {
			arg2 = args[2].(mqtt.MessageHandler)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMQTT_Subscribe_Call) Return(err error) *MockMQTT_Subscribe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMQTT_Subscribe_Call) RunAndReturn(run func(topic string, qos byte, messageHandler mqtt.MessageHandler) error) *MockMQTT_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}
