// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockdatabase

import (
	"context"
	"open-fermentations/internal/database"
	"open-fermentations/internal/database/sqlc"
	"open-fermentations/internal/dto"
	"open-fermentations/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockService
func (_mock *MockService) Close() {
	_mock.Called()
	return
}

// MockService_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockService_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockService_Expecter) Close() *MockService_Close_Call {
	return &MockService_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockService_Close_Call) Run(run func()) *MockService_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Close_Call) Return() *MockService_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_Close_Call) RunAndReturn(run func()) *MockService_Close_Call {
	_c.Run(run)
	return _c
}

// Health provides a mock function for the type MockService
func (_mock *MockService) Health() map[string]string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Health")
	}

	var r0 map[string]string
	if returnFunc, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	return r0
}

// MockService_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type MockService_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
func (_e *MockService_Expecter) Health() *MockService_Health_Call {
	return &MockService_Health_Call{Call: _e.mock.On("Health")}
}

func (_c *MockService_Health_Call) Run(run func()) *MockService_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Health_Call) Return(stringToString map[string]string) *MockService_Health_Call {
	_c.Call.Return(stringToString)
	return _c
}

func (_c *MockService_Health_Call) RunAndReturn(run func() map[string]string) *MockService_Health_Call {
	_c.Call.Return(run)
	return _c
}

// Querier provides a mock function for the type MockService
func (_mock *MockService) Querier() sqlc.Querier {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Querier")
	}

	var r0 sqlc.Querier
	if returnFunc, ok := ret.Get(0).(func() sqlc.Querier); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sqlc.Querier)
		}
	}
	return r0
}

// MockService_Querier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Querier'
type MockService_Querier_Call struct {
	*mock.Call
}

// Querier is a helper method to define mock.On call
func (_e *MockService_Expecter) Querier() *MockService_Querier_Call {
	return &MockService_Querier_Call{Call: _e.mock.On("Querier")}
}

func (_c *MockService_Querier_Call) Run(run func()) *MockService_Querier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Querier_Call) Return(querier sqlc.Querier) *MockService_Querier_Call {
	_c.Call.Return(querier)
	return _c
}

func (_c *MockService_Querier_Call) RunAndReturn(run func() sqlc.Querier) *MockService_Querier_Call {
	_c.Call.Return(run)
	return _c
}

// SearchDevices provides a mock function for the type MockService
func (_mock *MockService) SearchDevices(ctx context.Context, arg database.SearchDevicesParams) (*dto.PageDTO[model.Device], error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for SearchDevices")
	}

	var r0 *dto.PageDTO[model.Device]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.SearchDevicesParams) (*dto.PageDTO[model.Device], error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.SearchDevicesParams) *dto.PageDTO[model.Device]); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PageDTO[model.Device])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, database.SearchDevicesParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_SearchDevices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchDevices'
type MockService_SearchDevices_Call struct {
	*mock.Call
}

// SearchDevices is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.SearchDevicesParams
func (_e *MockService_Expecter) SearchDevices(ctx any, arg any) *MockService_SearchDevices_Call {
	return &MockService_SearchDevices_Call{Call: _e.mock.On("SearchDevices", ctx, arg)}
}

func (_c *MockService_SearchDevices_Call) Run(run func(ctx context.Context, arg database.SearchDevicesParams)) *MockService_SearchDevices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 database.SearchDevicesParams
		if args[1] != nil {
			arg1 = args[1].(database.SearchDevicesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_SearchDevices_Call) Return(pageDTO *dto.PageDTO[model.Device], err error) *MockService_SearchDevices_Call {
	_c.Call.Return(pageDTO, err)
	return _c
}

func (_c *MockService_SearchDevices_Call) RunAndReturn(run func(ctx context.Context, arg database.SearchDevicesParams) (*dto.PageDTO[model.Device], error)) *MockService_SearchDevices_Call {
	_c.Call.Return(run)
	return _c
}
