// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockdatabase

import (
	"open-fermentations/internal/database/sqlc"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockService
func (_mock *MockService) Close() {
	_mock.Called()
	return
}

// MockService_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockService_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockService_Expecter) Close() *MockService_Close_Call {
	return &MockService_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockService_Close_Call) Run(run func()) *MockService_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Close_Call) Return() *MockService_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_Close_Call) RunAndReturn(run func()) *MockService_Close_Call {
	_c.Run(run)
	return _c
}

// Health provides a mock function for the type MockService
func (_mock *MockService) Health() map[string]string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Health")
	}

	var r0 map[string]string
	if returnFunc, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	return r0
}

// MockService_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type MockService_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
func (_e *MockService_Expecter) Health() *MockService_Health_Call {
	return &MockService_Health_Call{Call: _e.mock.On("Health")}
}

func (_c *MockService_Health_Call) Run(run func()) *MockService_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Health_Call) Return(stringToString map[string]string) *MockService_Health_Call {
	_c.Call.Return(stringToString)
	return _c
}

func (_c *MockService_Health_Call) RunAndReturn(run func() map[string]string) *MockService_Health_Call {
	_c.Call.Return(run)
	return _c
}

// Queries provides a mock function for the type MockService
func (_mock *MockService) Queries() *sqlc.Queries {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Queries")
	}

	var r0 *sqlc.Queries
	if returnFunc, ok := ret.Get(0).(func() *sqlc.Queries); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlc.Queries)
		}
	}
	return r0
}

// MockService_Queries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Queries'
type MockService_Queries_Call struct {
	*mock.Call
}

// Queries is a helper method to define mock.On call
func (_e *MockService_Expecter) Queries() *MockService_Queries_Call {
	return &MockService_Queries_Call{Call: _e.mock.On("Queries")}
}

func (_c *MockService_Queries_Call) Run(run func()) *MockService_Queries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Queries_Call) Return(queries *sqlc.Queries) *MockService_Queries_Call {
	_c.Call.Return(queries)
	return _c
}

func (_c *MockService_Queries_Call) RunAndReturn(run func() *sqlc.Queries) *MockService_Queries_Call {
	_c.Call.Return(run)
	return _c
}
