// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :exec
insert into "user" (username, password)
values ($1, $2)
`

type CreateUserParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.Username, arg.Password)
	return err
}

const getUserById = `-- name: GetUserById :one
select id, username, created, modified
from "user"
where id = $1
`

type GetUserByIdRow struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
	Created  time.Time `json:"created"`
	Modified time.Time `json:"modified"`
}

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (GetUserByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Created,
		&i.Modified,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
select id, username, created, modified
from "user"
where username = $1
`

type GetUserByUsernameRow struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
	Created  time.Time `json:"created"`
	Modified time.Time `json:"modified"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Created,
		&i.Modified,
	)
	return i, err
}
