// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockservice

import (
	"open-fermentations/internal/dto"
	"open-fermentations/internal/model"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateBatches provides a mock function for the type MockService
func (_mock *MockService) CreateBatches(userId uuid.UUID, d []dto.CreateBatchDTO) ([]model.Batch, error) {
	ret := _mock.Called(userId, d)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatches")
	}

	var r0 []model.Batch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, []dto.CreateBatchDTO) ([]model.Batch, error)); ok {
		return returnFunc(userId, d)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, []dto.CreateBatchDTO) []model.Batch); ok {
		r0 = returnFunc(userId, d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Batch)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, []dto.CreateBatchDTO) error); ok {
		r1 = returnFunc(userId, d)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateBatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatches'
type MockService_CreateBatches_Call struct {
	*mock.Call
}

// CreateBatches is a helper method to define mock.On call
//   - userId uuid.UUID
//   - d []dto.CreateBatchDTO
func (_e *MockService_Expecter) CreateBatches(userId any, d any) *MockService_CreateBatches_Call {
	return &MockService_CreateBatches_Call{Call: _e.mock.On("CreateBatches", userId, d)}
}

func (_c *MockService_CreateBatches_Call) Run(run func(userId uuid.UUID, d []dto.CreateBatchDTO)) *MockService_CreateBatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 []dto.CreateBatchDTO
		if args[1] != nil {
			arg1 = args[1].([]dto.CreateBatchDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CreateBatches_Call) Return(batchs []model.Batch, err error) *MockService_CreateBatches_Call {
	_c.Call.Return(batchs, err)
	return _c
}

func (_c *MockService_CreateBatches_Call) RunAndReturn(run func(userId uuid.UUID, d []dto.CreateBatchDTO) ([]model.Batch, error)) *MockService_CreateBatches_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDevices provides a mock function for the type MockService
func (_mock *MockService) CreateDevices(userId uuid.UUID, d []dto.CreateDeviceDTO) ([]model.Device, error) {
	ret := _mock.Called(userId, d)

	if len(ret) == 0 {
		panic("no return value specified for CreateDevices")
	}

	var r0 []model.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, []dto.CreateDeviceDTO) ([]model.Device, error)); ok {
		return returnFunc(userId, d)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, []dto.CreateDeviceDTO) []model.Device); ok {
		r0 = returnFunc(userId, d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Device)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, []dto.CreateDeviceDTO) error); ok {
		r1 = returnFunc(userId, d)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateDevices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDevices'
type MockService_CreateDevices_Call struct {
	*mock.Call
}

// CreateDevices is a helper method to define mock.On call
//   - userId uuid.UUID
//   - d []dto.CreateDeviceDTO
func (_e *MockService_Expecter) CreateDevices(userId any, d any) *MockService_CreateDevices_Call {
	return &MockService_CreateDevices_Call{Call: _e.mock.On("CreateDevices", userId, d)}
}

func (_c *MockService_CreateDevices_Call) Run(run func(userId uuid.UUID, d []dto.CreateDeviceDTO)) *MockService_CreateDevices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 []dto.CreateDeviceDTO
		if args[1] != nil {
			arg1 = args[1].([]dto.CreateDeviceDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CreateDevices_Call) Return(devices []model.Device, err error) *MockService_CreateDevices_Call {
	_c.Call.Return(devices, err)
	return _c
}

func (_c *MockService_CreateDevices_Call) RunAndReturn(run func(userId uuid.UUID, d []dto.CreateDeviceDTO) ([]model.Device, error)) *MockService_CreateDevices_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBatch provides a mock function for the type MockService
func (_mock *MockService) DeleteBatch(id uuid.UUID) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBatch'
type MockService_DeleteBatch_Call struct {
	*mock.Call
}

// DeleteBatch is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockService_Expecter) DeleteBatch(id any) *MockService_DeleteBatch_Call {
	return &MockService_DeleteBatch_Call{Call: _e.mock.On("DeleteBatch", id)}
}

func (_c *MockService_DeleteBatch_Call) Run(run func(id uuid.UUID)) *MockService_DeleteBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_DeleteBatch_Call) Return(err error) *MockService_DeleteBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteBatch_Call) RunAndReturn(run func(id uuid.UUID) error) *MockService_DeleteBatch_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDevice provides a mock function for the type MockService
func (_mock *MockService) DeleteDevice(id uuid.UUID) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDevice")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDevice'
type MockService_DeleteDevice_Call struct {
	*mock.Call
}

// DeleteDevice is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockService_Expecter) DeleteDevice(id any) *MockService_DeleteDevice_Call {
	return &MockService_DeleteDevice_Call{Call: _e.mock.On("DeleteDevice", id)}
}

func (_c *MockService_DeleteDevice_Call) Run(run func(id uuid.UUID)) *MockService_DeleteDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_DeleteDevice_Call) Return(err error) *MockService_DeleteDevice_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteDevice_Call) RunAndReturn(run func(id uuid.UUID) error) *MockService_DeleteDevice_Call {
	_c.Call.Return(run)
	return _c
}

// GetBatchById provides a mock function for the type MockService
func (_mock *MockService) GetBatchById(id uuid.UUID) (*model.Batch, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetBatchById")
	}

	var r0 *model.Batch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*model.Batch, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *model.Batch); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Batch)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetBatchById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBatchById'
type MockService_GetBatchById_Call struct {
	*mock.Call
}

// GetBatchById is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockService_Expecter) GetBatchById(id any) *MockService_GetBatchById_Call {
	return &MockService_GetBatchById_Call{Call: _e.mock.On("GetBatchById", id)}
}

func (_c *MockService_GetBatchById_Call) Run(run func(id uuid.UUID)) *MockService_GetBatchById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetBatchById_Call) Return(batch *model.Batch, err error) *MockService_GetBatchById_Call {
	_c.Call.Return(batch, err)
	return _c
}

func (_c *MockService_GetBatchById_Call) RunAndReturn(run func(id uuid.UUID) (*model.Batch, error)) *MockService_GetBatchById_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeviceById provides a mock function for the type MockService
func (_mock *MockService) GetDeviceById(id uuid.UUID) (*model.Device, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetDeviceById")
	}

	var r0 *model.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*model.Device, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *model.Device); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Device)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetDeviceById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeviceById'
type MockService_GetDeviceById_Call struct {
	*mock.Call
}

// GetDeviceById is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockService_Expecter) GetDeviceById(id any) *MockService_GetDeviceById_Call {
	return &MockService_GetDeviceById_Call{Call: _e.mock.On("GetDeviceById", id)}
}

func (_c *MockService_GetDeviceById_Call) Run(run func(id uuid.UUID)) *MockService_GetDeviceById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetDeviceById_Call) Return(device *model.Device, err error) *MockService_GetDeviceById_Call {
	_c.Call.Return(device, err)
	return _c
}

func (_c *MockService_GetDeviceById_Call) RunAndReturn(run func(id uuid.UUID) (*model.Device, error)) *MockService_GetDeviceById_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockService
func (_mock *MockService) Login(username string, password string) (*model.User, error) {
	ret := _mock.Called(username, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*model.User, error)); ok {
		return returnFunc(username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *model.User); ok {
		r0 = returnFunc(username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - username string
//   - password string
func (_e *MockService_Expecter) Login(username any, password any) *MockService_Login_Call {
	return &MockService_Login_Call{Call: _e.mock.On("Login", username, password)}
}

func (_c *MockService_Login_Call) Run(run func(username string, password string)) *MockService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Login_Call) Return(user *model.User, err error) *MockService_Login_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockService_Login_Call) RunAndReturn(run func(username string, password string) (*model.User, error)) *MockService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// SearchBatches provides a mock function for the type MockService
func (_mock *MockService) SearchBatches(name string, limit int, offset int) ([]model.Batch, int, error) {
	ret := _mock.Called(name, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for SearchBatches")
	}

	var r0 []model.Batch
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, int, int) ([]model.Batch, int, error)); ok {
		return returnFunc(name, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, int) []model.Batch); ok {
		r0 = returnFunc(name, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Batch)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, int) int); ok {
		r1 = returnFunc(name, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(string, int, int) error); ok {
		r2 = returnFunc(name, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_SearchBatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchBatches'
type MockService_SearchBatches_Call struct {
	*mock.Call
}

// SearchBatches is a helper method to define mock.On call
//   - name string
//   - limit int
//   - offset int
func (_e *MockService_Expecter) SearchBatches(name any, limit any, offset any) *MockService_SearchBatches_Call {
	return &MockService_SearchBatches_Call{Call: _e.mock.On("SearchBatches", name, limit, offset)}
}

func (_c *MockService_SearchBatches_Call) Run(run func(name string, limit int, offset int)) *MockService_SearchBatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_SearchBatches_Call) Return(batchs []model.Batch, n int, err error) *MockService_SearchBatches_Call {
	_c.Call.Return(batchs, n, err)
	return _c
}

func (_c *MockService_SearchBatches_Call) RunAndReturn(run func(name string, limit int, offset int) ([]model.Batch, int, error)) *MockService_SearchBatches_Call {
	_c.Call.Return(run)
	return _c
}

// SearchDevices provides a mock function for the type MockService
func (_mock *MockService) SearchDevices(searchDTO dto.SearchDTO) (*dto.PageDTO[model.Device], error) {
	ret := _mock.Called(searchDTO)

	if len(ret) == 0 {
		panic("no return value specified for SearchDevices")
	}

	var r0 *dto.PageDTO[model.Device]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(dto.SearchDTO) (*dto.PageDTO[model.Device], error)); ok {
		return returnFunc(searchDTO)
	}
	if returnFunc, ok := ret.Get(0).(func(dto.SearchDTO) *dto.PageDTO[model.Device]); ok {
		r0 = returnFunc(searchDTO)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PageDTO[model.Device])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(dto.SearchDTO) error); ok {
		r1 = returnFunc(searchDTO)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_SearchDevices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchDevices'
type MockService_SearchDevices_Call struct {
	*mock.Call
}

// SearchDevices is a helper method to define mock.On call
//   - searchDTO dto.SearchDTO
func (_e *MockService_Expecter) SearchDevices(searchDTO any) *MockService_SearchDevices_Call {
	return &MockService_SearchDevices_Call{Call: _e.mock.On("SearchDevices", searchDTO)}
}

func (_c *MockService_SearchDevices_Call) Run(run func(searchDTO dto.SearchDTO)) *MockService_SearchDevices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dto.SearchDTO
		if args[0] != nil {
			arg0 = args[0].(dto.SearchDTO)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_SearchDevices_Call) Return(pageDTO *dto.PageDTO[model.Device], err error) *MockService_SearchDevices_Call {
	_c.Call.Return(pageDTO, err)
	return _c
}

func (_c *MockService_SearchDevices_Call) RunAndReturn(run func(searchDTO dto.SearchDTO) (*dto.PageDTO[model.Device], error)) *MockService_SearchDevices_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBatch provides a mock function for the type MockService
func (_mock *MockService) UpdateBatch(id uuid.UUID, name string) (*model.Batch, error) {
	ret := _mock.Called(id, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBatch")
	}

	var r0 *model.Batch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, string) (*model.Batch, error)); ok {
		return returnFunc(id, name)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, string) *model.Batch); ok {
		r0 = returnFunc(id, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Batch)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, string) error); ok {
		r1 = returnFunc(id, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_UpdateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBatch'
type MockService_UpdateBatch_Call struct {
	*mock.Call
}

// UpdateBatch is a helper method to define mock.On call
//   - id uuid.UUID
//   - name string
func (_e *MockService_Expecter) UpdateBatch(id any, name any) *MockService_UpdateBatch_Call {
	return &MockService_UpdateBatch_Call{Call: _e.mock.On("UpdateBatch", id, name)}
}

func (_c *MockService_UpdateBatch_Call) Run(run func(id uuid.UUID, name string)) *MockService_UpdateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_UpdateBatch_Call) Return(batch *model.Batch, err error) *MockService_UpdateBatch_Call {
	_c.Call.Return(batch, err)
	return _c
}

func (_c *MockService_UpdateBatch_Call) RunAndReturn(run func(id uuid.UUID, name string) (*model.Batch, error)) *MockService_UpdateBatch_Call {
	_c.Call.Return(run)
	return _c
}
