// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockservice

import (
	"open-fermentations/internal/dto"
	"open-fermentations/internal/model"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateBatch provides a mock function for the type MockService
func (_mock *MockService) CreateBatch(id uuid.UUID, d []dto.CreateBatchDTO) ([]model.Batch, error) {
	ret := _mock.Called(id, d)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 []model.Batch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, []dto.CreateBatchDTO) ([]model.Batch, error)); ok {
		return returnFunc(id, d)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, []dto.CreateBatchDTO) []model.Batch); ok {
		r0 = returnFunc(id, d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Batch)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, []dto.CreateBatchDTO) error); ok {
		r1 = returnFunc(id, d)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatch'
type MockService_CreateBatch_Call struct {
	*mock.Call
}

// CreateBatch is a helper method to define mock.On call
//   - id uuid.UUID
//   - d []dto.CreateBatchDTO
func (_e *MockService_Expecter) CreateBatch(id any, d any) *MockService_CreateBatch_Call {
	return &MockService_CreateBatch_Call{Call: _e.mock.On("CreateBatch", id, d)}
}

func (_c *MockService_CreateBatch_Call) Run(run func(id uuid.UUID, d []dto.CreateBatchDTO)) *MockService_CreateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 []dto.CreateBatchDTO
		if args[1] != nil {
			arg1 = args[1].([]dto.CreateBatchDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CreateBatch_Call) Return(batchs []model.Batch, err error) *MockService_CreateBatch_Call {
	_c.Call.Return(batchs, err)
	return _c
}

func (_c *MockService_CreateBatch_Call) RunAndReturn(run func(id uuid.UUID, d []dto.CreateBatchDTO) ([]model.Batch, error)) *MockService_CreateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBatch provides a mock function for the type MockService
func (_mock *MockService) DeleteBatch(id uuid.UUID) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBatch'
type MockService_DeleteBatch_Call struct {
	*mock.Call
}

// DeleteBatch is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockService_Expecter) DeleteBatch(id any) *MockService_DeleteBatch_Call {
	return &MockService_DeleteBatch_Call{Call: _e.mock.On("DeleteBatch", id)}
}

func (_c *MockService_DeleteBatch_Call) Run(run func(id uuid.UUID)) *MockService_DeleteBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_DeleteBatch_Call) Return(err error) *MockService_DeleteBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteBatch_Call) RunAndReturn(run func(id uuid.UUID) error) *MockService_DeleteBatch_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockService
func (_mock *MockService) Login(username string, password string) (*model.User, error) {
	ret := _mock.Called(username, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*model.User, error)); ok {
		return returnFunc(username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *model.User); ok {
		r0 = returnFunc(username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - username string
//   - password string
func (_e *MockService_Expecter) Login(username any, password any) *MockService_Login_Call {
	return &MockService_Login_Call{Call: _e.mock.On("Login", username, password)}
}

func (_c *MockService_Login_Call) Run(run func(username string, password string)) *MockService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Login_Call) Return(user *model.User, err error) *MockService_Login_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockService_Login_Call) RunAndReturn(run func(username string, password string) (*model.User, error)) *MockService_Login_Call {
	_c.Call.Return(run)
	return _c
}
