// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBatch = `-- name: CreateBatch :one
insert into "batch" ("name", user_id)
values ($1, $2)
returning id, "name", user_id, created, modified
`

type CreateBatchParams struct {
	Name   string
	UserID uuid.UUID
}

// CreateBatch
//
//	insert into "batch" ("name", user_id)
//	values ($1, $2)
//	returning id, "name", user_id, created, modified
func (q *Queries) CreateBatch(ctx context.Context, arg CreateBatchParams) (Batch, error) {
	row := q.db.QueryRow(ctx, createBatch, arg.Name, arg.UserID)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Created,
		&i.Modified,
	)
	return i, err
}

const deleteBatch = `-- name: DeleteBatch :exec
delete from "batch" where id = $1 and user_id = $2
`

type DeleteBatchParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// DeleteBatch
//
//	delete from "batch" where id = $1 and user_id = $2
func (q *Queries) DeleteBatch(ctx context.Context, arg DeleteBatchParams) error {
	_, err := q.db.Exec(ctx, deleteBatch, arg.ID, arg.UserID)
	return err
}

const getBatchById = `-- name: GetBatchById :one
select id, name, user_id, created, modified from "batch" where id = $1 and user_id = $2
`

type GetBatchByIdParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// GetBatchById
//
//	select id, name, user_id, created, modified from "batch" where id = $1 and user_id = $2
func (q *Queries) GetBatchById(ctx context.Context, arg GetBatchByIdParams) (Batch, error) {
	row := q.db.QueryRow(ctx, getBatchById, arg.ID, arg.UserID)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Created,
		&i.Modified,
	)
	return i, err
}

const searchBatches = `-- name: SearchBatches :many
select id, name, user_id, created, modified, count(id) over() as total from "batch"
where user_id = $1
    AND "name" LIKE $2::text
order by created desc
limit $4::integer
offset $3::integer
`

type SearchBatchesParams struct {
	UserID    uuid.UUID
	Name      string
	Offsetval int32
	Limitval  int32
}

type SearchBatchesRow struct {
	ID       uuid.UUID
	Name     string
	UserID   uuid.UUID
	Created  time.Time
	Modified time.Time
	Total    int64
}

// SearchBatches
//
//	select id, name, user_id, created, modified, count(id) over() as total from "batch"
//	where user_id = $1
//	    AND "name" LIKE $2::text
//	order by created desc
//	limit $4::integer
//	offset $3::integer
func (q *Queries) SearchBatches(ctx context.Context, arg SearchBatchesParams) ([]SearchBatchesRow, error) {
	rows, err := q.db.Query(ctx, searchBatches,
		arg.UserID,
		arg.Name,
		arg.Offsetval,
		arg.Limitval,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchBatchesRow
	for rows.Next() {
		var i SearchBatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.Created,
			&i.Modified,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBatch = `-- name: UpdateBatch :one
update "batch" set "name" = $1, modified = current_timestamp where id = $2 and user_id = $3
returning id, name, user_id, created, modified
`

type UpdateBatchParams struct {
	Name   string
	ID     uuid.UUID
	UserID uuid.UUID
}

// UpdateBatch
//
//	update "batch" set "name" = $1, modified = current_timestamp where id = $2 and user_id = $3
//	returning id, name, user_id, created, modified
func (q *Queries) UpdateBatch(ctx context.Context, arg UpdateBatchParams) (Batch, error) {
	row := q.db.QueryRow(ctx, updateBatch, arg.Name, arg.ID, arg.UserID)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Created,
		&i.Modified,
	)
	return i, err
}
