// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createBatch = `-- name: CreateBatch :one
insert into "batch" ("name", user_id)
values ($1, $2)
returning id, "name", user_id, created, modified
`

type CreateBatchParams struct {
	Name   string
	UserID uuid.UUID
}

// CreateBatch
//
//	insert into "batch" ("name", user_id)
//	values ($1, $2)
//	returning id, "name", user_id, created, modified
func (q *Queries) CreateBatch(ctx context.Context, arg CreateBatchParams) (Batch, error) {
	row := q.db.QueryRow(ctx, createBatch, arg.Name, arg.UserID)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Created,
		&i.Modified,
	)
	return i, err
}

const deleteBatch = `-- name: DeleteBatch :exec
delete from "batch" where id = $1
`

// DeleteBatch
//
//	delete from "batch" where id = $1
func (q *Queries) DeleteBatch(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBatch, id)
	return err
}
