// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch_device.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addDeviceToBatch = `-- name: AddDeviceToBatch :one
insert into "batch_device" ("batch_id", "device_id") values ($1, $2)
returning id, batch_id, device_id, created, modified
`

type AddDeviceToBatchParams struct {
	BatchID  uuid.UUID
	DeviceID uuid.UUID
}

// AddDeviceToBatch
//
//	insert into "batch_device" ("batch_id", "device_id") values ($1, $2)
//	returning id, batch_id, device_id, created, modified
func (q *Queries) AddDeviceToBatch(ctx context.Context, arg AddDeviceToBatchParams) (BatchDevice, error) {
	row := q.db.QueryRow(ctx, addDeviceToBatch, arg.BatchID, arg.DeviceID)
	var i BatchDevice
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.DeviceID,
		&i.Created,
		&i.Modified,
	)
	return i, err
}
