// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: device.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDevice = `-- name: CreateDevice :one
insert into "device" ("name", mac_address, user_id)
values ($1, $2, $3)
returning id, "name", mac_address, user_id, created, modified
`

type CreateDeviceParams struct {
	Name       string
	MacAddress []byte
	UserID     uuid.UUID
}

// CreateDevice
//
//	insert into "device" ("name", mac_address, user_id)
//	values ($1, $2, $3)
//	returning id, "name", mac_address, user_id, created, modified
func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice, arg.Name, arg.MacAddress, arg.UserID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MacAddress,
		&i.UserID,
		&i.Created,
		&i.Modified,
	)
	return i, err
}

const getDeviceById = `-- name: GetDeviceById :one
select id, name, mac_address, user_id, created, modified from "device"
where id = $1
`

// GetDeviceById
//
//	select id, name, mac_address, user_id, created, modified from "device"
//	where id = $1
func (q *Queries) GetDeviceById(ctx context.Context, id uuid.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceById, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MacAddress,
		&i.UserID,
		&i.Created,
		&i.Modified,
	)
	return i, err
}

const removeDeviceById = `-- name: RemoveDeviceById :exec
delete from "device"
where id = $1
`

// RemoveDeviceById
//
//	delete from "device"
//	where id = $1
func (q *Queries) RemoveDeviceById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeDeviceById, id)
	return err
}

const searchDevices = `-- name: SearchDevices :many
select id, name, mac_address, user_id, created, modified, count(*) over() as total
from "device"
where "name" like $1::text
order by
  case when $2::text = 'name' and $3::bool then "device"."name" end asc nulls last,
  case when $2::text = 'name' and $3::bool != true then "device"."name" end desc nulls last,
  case when $2::text = 'created' and $3::bool then "device"."created" end asc nulls last,
  case when $2::text = 'created' and $3::bool != true then "device"."created" end desc nulls last,
  case when $2::text = 'modified' and $3::bool then "device"."modified" end asc nulls last,
  case when $2::text = 'modified' and $3::bool != true then "device"."modified" end desc nulls last,
  case when $2::text = 'id' and $3::bool then "device"."id" end asc nulls last,
  case when $2::text = 'id' and $3::bool != true then "device"."id" end desc nulls last,
  case when $2::text = 'user_id' and $3::bool then "device"."user_id" end asc nulls last,
  case when $2::text = 'user_id' and $3::bool != true then "device"."user_id" end desc nulls last,
  case when $2::text = 'mac_address' and $3::bool then "device"."mac_address" end asc nulls last,
  case when $2::text = 'mac_address' and $3::bool != true then "device"."mac_address" end desc nulls last,
  "device"."created" asc nulls last
limit $5
offset $4
`

type SearchDevicesParams struct {
	Search    string
	OrderCol  string
	Asc       bool
	Offsetval int32
	Limitval  int32
}

type SearchDevicesRow struct {
	ID         uuid.UUID
	Name       string
	MacAddress []byte
	UserID     uuid.UUID
	Created    time.Time
	Modified   time.Time
	Total      int64
}

// SearchDevices
//
//	select id, name, mac_address, user_id, created, modified, count(*) over() as total
//	from "device"
//	where "name" like $1::text
//	order by
//	  case when $2::text = 'name' and $3::bool then "device"."name" end asc nulls last,
//	  case when $2::text = 'name' and $3::bool != true then "device"."name" end desc nulls last,
//	  case when $2::text = 'created' and $3::bool then "device"."created" end asc nulls last,
//	  case when $2::text = 'created' and $3::bool != true then "device"."created" end desc nulls last,
//	  case when $2::text = 'modified' and $3::bool then "device"."modified" end asc nulls last,
//	  case when $2::text = 'modified' and $3::bool != true then "device"."modified" end desc nulls last,
//	  case when $2::text = 'id' and $3::bool then "device"."id" end asc nulls last,
//	  case when $2::text = 'id' and $3::bool != true then "device"."id" end desc nulls last,
//	  case when $2::text = 'user_id' and $3::bool then "device"."user_id" end asc nulls last,
//	  case when $2::text = 'user_id' and $3::bool != true then "device"."user_id" end desc nulls last,
//	  case when $2::text = 'mac_address' and $3::bool then "device"."mac_address" end asc nulls last,
//	  case when $2::text = 'mac_address' and $3::bool != true then "device"."mac_address" end desc nulls last,
//	  "device"."created" asc nulls last
//	limit $5
//	offset $4
func (q *Queries) SearchDevices(ctx context.Context, arg SearchDevicesParams) ([]SearchDevicesRow, error) {
	rows, err := q.db.Query(ctx, searchDevices,
		arg.Search,
		arg.OrderCol,
		arg.Asc,
		arg.Offsetval,
		arg.Limitval,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchDevicesRow
	for rows.Next() {
		var i SearchDevicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MacAddress,
			&i.UserID,
			&i.Created,
			&i.Modified,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDevice = `-- name: UpdateDevice :one
update "device" set "name" = $1::text, mac_address = $2, user_id = $3, modified = current_timestamp
where id = $4
returning id, name, mac_address, user_id, created, modified
`

type UpdateDeviceParams struct {
	Name       string
	Macaddress []byte
	UserID     uuid.UUID
	ID         uuid.UUID
}

// UpdateDevice
//
//	update "device" set "name" = $1::text, mac_address = $2, user_id = $3, modified = current_timestamp
//	where id = $4
//	returning id, name, mac_address, user_id, created, modified
func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDevice,
		arg.Name,
		arg.Macaddress,
		arg.UserID,
		arg.ID,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MacAddress,
		&i.UserID,
		&i.Created,
		&i.Modified,
	)
	return i, err
}
