// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: device.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createDevice = `-- name: CreateDevice :one
insert into "device" ("name", mac_address, user_id)
values ($1, $2, $3)
returning id, "name", mac_address, user_id, created, modified
`

type CreateDeviceParams struct {
	Name       string
	MacAddress []byte
	UserID     uuid.UUID
}

// CreateDevice
//
//	insert into "device" ("name", mac_address, user_id)
//	values ($1, $2, $3)
//	returning id, "name", mac_address, user_id, created, modified
func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice, arg.Name, arg.MacAddress, arg.UserID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MacAddress,
		&i.UserID,
		&i.Created,
		&i.Modified,
	)
	return i, err
}
