// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type ReadingTypeEnum string

const (
	ReadingTypeEnumTemperature ReadingTypeEnum = "temperature"
	ReadingTypeEnumGravity     ReadingTypeEnum = "gravity"
	ReadingTypeEnumVolume      ReadingTypeEnum = "volume"
	ReadingTypeEnumPressure    ReadingTypeEnum = "pressure"
	ReadingTypeEnumPh          ReadingTypeEnum = "ph"
)

func (e *ReadingTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReadingTypeEnum(s)
	case string:
		*e = ReadingTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ReadingTypeEnum: %T", src)
	}
	return nil
}

type NullReadingTypeEnum struct {
	ReadingTypeEnum ReadingTypeEnum `json:"reading_type_enum"`
	Valid           bool            `json:"valid"` // Valid is true if ReadingTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReadingTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ReadingTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReadingTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReadingTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReadingTypeEnum), nil
}

type Batch struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	UserID   uuid.UUID `json:"user_id"`
	Created  time.Time `json:"created"`
	Modified time.Time `json:"modified"`
}

type BatchReading struct {
	ID       uuid.UUID `json:"id"`
	BatchID  uuid.UUID `json:"batch_id"`
	UserID   uuid.UUID `json:"user_id"`
	Created  time.Time `json:"created"`
	Modified time.Time `json:"modified"`
}

type Device struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	MacAddress []byte    `json:"mac_address"`
	UserID     uuid.UUID `json:"user_id"`
	Created    time.Time `json:"created"`
	Modified   time.Time `json:"modified"`
}

type DeviceCapability struct {
	ID         uuid.UUID       `json:"id"`
	DeviceID   uuid.UUID       `json:"device_id"`
	Capability ReadingTypeEnum `json:"capability"`
	Created    time.Time       `json:"created"`
	Modified   time.Time       `json:"modified"`
}

type Permission struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type Reading struct {
	ID          uuid.UUID       `json:"id"`
	ReadingType ReadingTypeEnum `json:"reading_type"`
	Value       float32         `json:"value"`
	DeviceID    uuid.UUID       `json:"device_id"`
	UserID      uuid.UUID       `json:"user_id"`
	Created     time.Time       `json:"created"`
	Modified    time.Time       `json:"modified"`
}

type Role struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type RolePermission struct {
	ID           uuid.UUID `json:"id"`
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type User struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
	Password string    `json:"password"`
	Active   bool      `json:"active"`
	Created  time.Time `json:"created"`
	Modified time.Time `json:"modified"`
}
