// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type ReadingTypeEnum string

const (
	ReadingTypeEnumTemperature ReadingTypeEnum = "temperature"
	ReadingTypeEnumGravity     ReadingTypeEnum = "gravity"
	ReadingTypeEnumVolume      ReadingTypeEnum = "volume"
	ReadingTypeEnumPressure    ReadingTypeEnum = "pressure"
	ReadingTypeEnumPh          ReadingTypeEnum = "ph"
)

func (e *ReadingTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReadingTypeEnum(s)
	case string:
		*e = ReadingTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ReadingTypeEnum: %T", src)
	}
	return nil
}

type NullReadingTypeEnum struct {
	ReadingTypeEnum ReadingTypeEnum
	Valid           bool // Valid is true if ReadingTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReadingTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ReadingTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReadingTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReadingTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReadingTypeEnum), nil
}

type Batch struct {
	ID       uuid.UUID
	Name     string
	UserID   uuid.UUID
	Created  time.Time
	Modified time.Time
}

type BatchDevice struct {
	ID       uuid.UUID
	BatchID  uuid.UUID
	DeviceID uuid.UUID
	Created  time.Time
	Modified time.Time
}

type BatchReading struct {
	ID        uuid.UUID
	BatchID   uuid.UUID
	UserID    uuid.UUID
	ReadingID uuid.UUID
	Created   time.Time
	Modified  time.Time
}

type Device struct {
	ID         uuid.UUID
	Name       string
	MacAddress string
	UserID     uuid.UUID
	Created    time.Time
	Modified   time.Time
}

type DeviceCapability struct {
	ID         uuid.UUID
	DeviceID   uuid.UUID
	Capability ReadingTypeEnum
	Created    time.Time
	Modified   time.Time
}

type Permission struct {
	ID   uuid.UUID
	Name string
}

type Reading struct {
	ID          uuid.UUID
	ReadingType ReadingTypeEnum
	Value       float64
	DeviceID    uuid.UUID
	UserID      uuid.UUID
	Created     time.Time
	Modified    time.Time
}

type Role struct {
	ID   uuid.UUID
	Name string
}

type RolePermission struct {
	ID           uuid.UUID
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

type User struct {
	ID       uuid.UUID
	Username string
	Password string
	Active   bool
	Created  time.Time
	Modified time.Time
}

type UserPermission struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	PermissionID uuid.UUID
}

type UserRole struct {
	ID     uuid.UUID
	UserID uuid.UUID
	RoleID uuid.UUID
}
