// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role.sql

package sqlc

import (
	"context"
)

const getRolesWithPermissions = `-- name: GetRolesWithPermissions :many
select r.id, r.name, p.id, p.name
from "role" r
left join "permission" p on r.id = p.role_id
`

type GetRolesWithPermissionsRow struct {
	Role       Role
	Permission Permission
}

// GetRolesWithPermissions
//
//	select r.id, r.name, p.id, p.name
//	from "role" r
//	left join "permission" p on r.id = p.role_id
func (q *Queries) GetRolesWithPermissions(ctx context.Context) ([]GetRolesWithPermissionsRow, error) {
	rows, err := q.db.Query(ctx, getRolesWithPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRolesWithPermissionsRow
	for rows.Next() {
		var i GetRolesWithPermissionsRow
		if err := rows.Scan(
			&i.Role.ID,
			&i.Role.Name,
			&i.Permission.ID,
			&i.Permission.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
