// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :exec
insert into "user" (username, password)
values ($1, $2)
`

type CreateUserParams struct {
	Username string
	Password string
}

// CreateUser
//
//	insert into "user" (username, password)
//	values ($1, $2)
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.Username, arg.Password)
	return err
}

const getUserById = `-- name: GetUserById :one
select id, username, created, modified
from "user"
where id = $1
`

type GetUserByIdRow struct {
	ID       uuid.UUID
	Username string
	Created  time.Time
	Modified time.Time
}

// GetUserById
//
//	select id, username, created, modified
//	from "user"
//	where id = $1
func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (GetUserByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Created,
		&i.Modified,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
select id, username, password, active, created, modified
from "user"
where username = $1
`

// GetUserByUsername
//
//	select id, username, password, active, created, modified
//	from "user"
//	where username = $1
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Active,
		&i.Created,
		&i.Modified,
	)
	return i, err
}

const getUserByUsernameWithPasswordAndRolesAndPermissions = `-- name: GetUserByUsernameWithPasswordAndRolesAndPermissions :many
select u.id, u.username, u.password, u.active, u.created, u.modified, r.id, r.name, p.id, p.name 
from "user" u 
left join "user_role" ur on ur.user_id = u.id 
left join "user_permission" up on up.user_id = u.id 
left join "role" r on ur.role_id = r.id 
left join "role_permission" rp on r.id = rp.role_id 
left join "permission" p on up.permission_id = p.id or p.id = rp.permission_id 
where username = $1
`

type GetUserByUsernameWithPasswordAndRolesAndPermissionsRow struct {
	User       User
	Role       Role
	Permission Permission
}

// GetUserByUsernameWithPasswordAndRolesAndPermissions
//
//	select u.id, u.username, u.password, u.active, u.created, u.modified, r.id, r.name, p.id, p.name
//	from "user" u
//	left join "user_role" ur on ur.user_id = u.id
//	left join "user_permission" up on up.user_id = u.id
//	left join "role" r on ur.role_id = r.id
//	left join "role_permission" rp on r.id = rp.role_id
//	left join "permission" p on up.permission_id = p.id or p.id = rp.permission_id
//	where username = $1
func (q *Queries) GetUserByUsernameWithPasswordAndRolesAndPermissions(ctx context.Context, username string) ([]GetUserByUsernameWithPasswordAndRolesAndPermissionsRow, error) {
	rows, err := q.db.Query(ctx, getUserByUsernameWithPasswordAndRolesAndPermissions, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserByUsernameWithPasswordAndRolesAndPermissionsRow
	for rows.Next() {
		var i GetUserByUsernameWithPasswordAndRolesAndPermissionsRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.Username,
			&i.User.Password,
			&i.User.Active,
			&i.User.Created,
			&i.User.Modified,
			&i.Role.ID,
			&i.Role.Name,
			&i.Permission.ID,
			&i.Permission.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
