@id=db05cb71-31d6-4e0c-8cbf-cde3bccafc2e
@deviceId=3c700a4b-339b-4fb8-9677-cb060a3e03cb
### Create batch
POST {{url}}/api/batch
Content-Type: application/json

[{
  "name": "first batch"
}]

### Delete batch
DELETE {{url}}/api/batch/{{id}}

### Get batches
GET {{url}}/api/batch

### Get batch
GET {{url}}/api/batch/{{id}}

### Update batch
PUT {{url}}/api/batch/{{id}}
Content-Type: application/json

{
  "name": "new name"
}

### Add device to batch
PUT {{url}}/api/batch/{{id}}/device/{{deviceId}}
