@id=9ea8ade8-190e-4fad-af41-d85fbd648dff
### Create batch
POST {{url}}/api/batch
Content-Type: application/json

[{
  "name": "first batch"
}]

### Delete batch
DELETE {{url}}/api/batch/{{id}}

### Get batches
GET {{url}}/api/batch

### Get batch
GET {{url}}/api/batch/{{id}}

### Update batch
PUT {{url}}/api/batch/{{id}}
Content-Type: application/json

{
  "name": "new name"
}