@id=7cc0046c-0946-4e8d-9c82-d675ba9121b2
### Create devices
POST {{url}}/api/device
Content-Type: application/json

[{
  "name":"Z it starts with z",
  "macAddress": "3B-FB-19-6A-92-61"
}]

### Search devices
GET {{url}}/api/device?orderBy=id&asc=true

### Get Device by id
GET {{url}}/api/device/{{id}}

### Delete Device by id
DELETE {{url}}/api/device/{{id}}

### Update Device
PUT {{url}}/api/device/{{id}}
Content-Type: application/json

{
  "name": "some new name",
  "macAddress": "3B-FB-19-6A-92-63",
  "userId": "1d48244c-9d22-4da4-90f3-50c28898bf87"
}