@id=e4e2668c-9091-4a49-a6d8-cb82629c50df
### Create devices
POST {{url}}/api/device
Content-Type: application/json

[{
  "name":"Z it starts with z",
  "macAddress": "3B-FB-19-6A-92-61"
}]

### Search devices
GET {{url}}/api/device?orderBy=id&asc=true

### Get Device by id
GET {{url}}/api/device/{{id}}

### Delete Device by id
DELETE {{url}}/api/device/{{id}}

### Update Device
PUT {{url}}/api/device/{{id}}
Content-Type: application/json

{
  "name": "some new name",
  "macAddress": "3B-FB-19-6A-92-63"
}