// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocksqlc

import (
	"context"
	"open-fermentations/internal/database/sqlc"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// CreateBatch provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateBatch(ctx context.Context, arg sqlc.CreateBatchParams) (sqlc.Batch, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 sqlc.Batch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateBatchParams) (sqlc.Batch, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateBatchParams) sqlc.Batch); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.Batch)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.CreateBatchParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CreateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatch'
type MockQuerier_CreateBatch_Call struct {
	*mock.Call
}

// CreateBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.CreateBatchParams
func (_e *MockQuerier_Expecter) CreateBatch(ctx any, arg any) *MockQuerier_CreateBatch_Call {
	return &MockQuerier_CreateBatch_Call{Call: _e.mock.On("CreateBatch", ctx, arg)}
}

func (_c *MockQuerier_CreateBatch_Call) Run(run func(ctx context.Context, arg sqlc.CreateBatchParams)) *MockQuerier_CreateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CreateBatchParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CreateBatchParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateBatch_Call) Return(batch sqlc.Batch, err error) *MockQuerier_CreateBatch_Call {
	_c.Call.Return(batch, err)
	return _c
}

func (_c *MockQuerier_CreateBatch_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.CreateBatchParams) (sqlc.Batch, error)) *MockQuerier_CreateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDevice provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateDevice(ctx context.Context, arg sqlc.CreateDeviceParams) (sqlc.Device, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateDevice")
	}

	var r0 sqlc.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateDeviceParams) (sqlc.Device, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateDeviceParams) sqlc.Device); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.Device)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.CreateDeviceParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CreateDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDevice'
type MockQuerier_CreateDevice_Call struct {
	*mock.Call
}

// CreateDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.CreateDeviceParams
func (_e *MockQuerier_Expecter) CreateDevice(ctx any, arg any) *MockQuerier_CreateDevice_Call {
	return &MockQuerier_CreateDevice_Call{Call: _e.mock.On("CreateDevice", ctx, arg)}
}

func (_c *MockQuerier_CreateDevice_Call) Run(run func(ctx context.Context, arg sqlc.CreateDeviceParams)) *MockQuerier_CreateDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CreateDeviceParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CreateDeviceParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateDevice_Call) Return(device sqlc.Device, err error) *MockQuerier_CreateDevice_Call {
	_c.Call.Return(device, err)
	return _c
}

func (_c *MockQuerier_CreateDevice_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.CreateDeviceParams) (sqlc.Device, error)) *MockQuerier_CreateDevice_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateUser(ctx context.Context, arg sqlc.CreateUserParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateUserParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockQuerier_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.CreateUserParams
func (_e *MockQuerier_Expecter) CreateUser(ctx any, arg any) *MockQuerier_CreateUser_Call {
	return &MockQuerier_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, arg)}
}

func (_c *MockQuerier_CreateUser_Call) Run(run func(ctx context.Context, arg sqlc.CreateUserParams)) *MockQuerier_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CreateUserParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CreateUserParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateUser_Call) Return(err error) *MockQuerier_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_CreateUser_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.CreateUserParams) error) *MockQuerier_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBatch provides a mock function for the type MockQuerier
func (_mock *MockQuerier) DeleteBatch(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_DeleteBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBatch'
type MockQuerier_DeleteBatch_Call struct {
	*mock.Call
}

// DeleteBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockQuerier_Expecter) DeleteBatch(ctx any, id any) *MockQuerier_DeleteBatch_Call {
	return &MockQuerier_DeleteBatch_Call{Call: _e.mock.On("DeleteBatch", ctx, id)}
}

func (_c *MockQuerier_DeleteBatch_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockQuerier_DeleteBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_DeleteBatch_Call) Return(err error) *MockQuerier_DeleteBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_DeleteBatch_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockQuerier_DeleteBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetBatchById provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetBatchById(ctx context.Context, id uuid.UUID) (sqlc.Batch, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBatchById")
	}

	var r0 sqlc.Batch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (sqlc.Batch, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) sqlc.Batch); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlc.Batch)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetBatchById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBatchById'
type MockQuerier_GetBatchById_Call struct {
	*mock.Call
}

// GetBatchById is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockQuerier_Expecter) GetBatchById(ctx any, id any) *MockQuerier_GetBatchById_Call {
	return &MockQuerier_GetBatchById_Call{Call: _e.mock.On("GetBatchById", ctx, id)}
}

func (_c *MockQuerier_GetBatchById_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockQuerier_GetBatchById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetBatchById_Call) Return(batch sqlc.Batch, err error) *MockQuerier_GetBatchById_Call {
	_c.Call.Return(batch, err)
	return _c
}

func (_c *MockQuerier_GetBatchById_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (sqlc.Batch, error)) *MockQuerier_GetBatchById_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserById provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetUserById(ctx context.Context, id uuid.UUID) (sqlc.GetUserByIdRow, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserById")
	}

	var r0 sqlc.GetUserByIdRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (sqlc.GetUserByIdRow, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) sqlc.GetUserByIdRow); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlc.GetUserByIdRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetUserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserById'
type MockQuerier_GetUserById_Call struct {
	*mock.Call
}

// GetUserById is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockQuerier_Expecter) GetUserById(ctx any, id any) *MockQuerier_GetUserById_Call {
	return &MockQuerier_GetUserById_Call{Call: _e.mock.On("GetUserById", ctx, id)}
}

func (_c *MockQuerier_GetUserById_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockQuerier_GetUserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetUserById_Call) Return(getUserByIdRow sqlc.GetUserByIdRow, err error) *MockQuerier_GetUserById_Call {
	_c.Call.Return(getUserByIdRow, err)
	return _c
}

func (_c *MockQuerier_GetUserById_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (sqlc.GetUserByIdRow, error)) *MockQuerier_GetUserById_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUsername provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetUserByUsername(ctx context.Context, username string) (sqlc.GetUserByUsernameRow, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 sqlc.GetUserByUsernameRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (sqlc.GetUserByUsernameRow, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) sqlc.GetUserByUsernameRow); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(sqlc.GetUserByUsernameRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsername'
type MockQuerier_GetUserByUsername_Call struct {
	*mock.Call
}

// GetUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockQuerier_Expecter) GetUserByUsername(ctx any, username any) *MockQuerier_GetUserByUsername_Call {
	return &MockQuerier_GetUserByUsername_Call{Call: _e.mock.On("GetUserByUsername", ctx, username)}
}

func (_c *MockQuerier_GetUserByUsername_Call) Run(run func(ctx context.Context, username string)) *MockQuerier_GetUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetUserByUsername_Call) Return(getUserByUsernameRow sqlc.GetUserByUsernameRow, err error) *MockQuerier_GetUserByUsername_Call {
	_c.Call.Return(getUserByUsernameRow, err)
	return _c
}

func (_c *MockQuerier_GetUserByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (sqlc.GetUserByUsernameRow, error)) *MockQuerier_GetUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUsernameWithPassword provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetUserByUsernameWithPassword(ctx context.Context, username string) (sqlc.GetUserByUsernameWithPasswordRow, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsernameWithPassword")
	}

	var r0 sqlc.GetUserByUsernameWithPasswordRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (sqlc.GetUserByUsernameWithPasswordRow, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) sqlc.GetUserByUsernameWithPasswordRow); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(sqlc.GetUserByUsernameWithPasswordRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetUserByUsernameWithPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsernameWithPassword'
type MockQuerier_GetUserByUsernameWithPassword_Call struct {
	*mock.Call
}

// GetUserByUsernameWithPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockQuerier_Expecter) GetUserByUsernameWithPassword(ctx any, username any) *MockQuerier_GetUserByUsernameWithPassword_Call {
	return &MockQuerier_GetUserByUsernameWithPassword_Call{Call: _e.mock.On("GetUserByUsernameWithPassword", ctx, username)}
}

func (_c *MockQuerier_GetUserByUsernameWithPassword_Call) Run(run func(ctx context.Context, username string)) *MockQuerier_GetUserByUsernameWithPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetUserByUsernameWithPassword_Call) Return(getUserByUsernameWithPasswordRow sqlc.GetUserByUsernameWithPasswordRow, err error) *MockQuerier_GetUserByUsernameWithPassword_Call {
	_c.Call.Return(getUserByUsernameWithPasswordRow, err)
	return _c
}

func (_c *MockQuerier_GetUserByUsernameWithPassword_Call) RunAndReturn(run func(ctx context.Context, username string) (sqlc.GetUserByUsernameWithPasswordRow, error)) *MockQuerier_GetUserByUsernameWithPassword_Call {
	_c.Call.Return(run)
	return _c
}

// SearchBatches provides a mock function for the type MockQuerier
func (_mock *MockQuerier) SearchBatches(ctx context.Context, arg sqlc.SearchBatchesParams) ([]sqlc.SearchBatchesRow, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for SearchBatches")
	}

	var r0 []sqlc.SearchBatchesRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.SearchBatchesParams) ([]sqlc.SearchBatchesRow, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.SearchBatchesParams) []sqlc.SearchBatchesRow); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.SearchBatchesRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.SearchBatchesParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_SearchBatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchBatches'
type MockQuerier_SearchBatches_Call struct {
	*mock.Call
}

// SearchBatches is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.SearchBatchesParams
func (_e *MockQuerier_Expecter) SearchBatches(ctx any, arg any) *MockQuerier_SearchBatches_Call {
	return &MockQuerier_SearchBatches_Call{Call: _e.mock.On("SearchBatches", ctx, arg)}
}

func (_c *MockQuerier_SearchBatches_Call) Run(run func(ctx context.Context, arg sqlc.SearchBatchesParams)) *MockQuerier_SearchBatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.SearchBatchesParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.SearchBatchesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_SearchBatches_Call) Return(searchBatchesRows []sqlc.SearchBatchesRow, err error) *MockQuerier_SearchBatches_Call {
	_c.Call.Return(searchBatchesRows, err)
	return _c
}

func (_c *MockQuerier_SearchBatches_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.SearchBatchesParams) ([]sqlc.SearchBatchesRow, error)) *MockQuerier_SearchBatches_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBatch provides a mock function for the type MockQuerier
func (_mock *MockQuerier) UpdateBatch(ctx context.Context, arg sqlc.UpdateBatchParams) (sqlc.Batch, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBatch")
	}

	var r0 sqlc.Batch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateBatchParams) (sqlc.Batch, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateBatchParams) sqlc.Batch); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.Batch)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.UpdateBatchParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_UpdateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBatch'
type MockQuerier_UpdateBatch_Call struct {
	*mock.Call
}

// UpdateBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.UpdateBatchParams
func (_e *MockQuerier_Expecter) UpdateBatch(ctx any, arg any) *MockQuerier_UpdateBatch_Call {
	return &MockQuerier_UpdateBatch_Call{Call: _e.mock.On("UpdateBatch", ctx, arg)}
}

func (_c *MockQuerier_UpdateBatch_Call) Run(run func(ctx context.Context, arg sqlc.UpdateBatchParams)) *MockQuerier_UpdateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.UpdateBatchParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.UpdateBatchParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_UpdateBatch_Call) Return(batch sqlc.Batch, err error) *MockQuerier_UpdateBatch_Call {
	_c.Call.Return(batch, err)
	return _c
}

func (_c *MockQuerier_UpdateBatch_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.UpdateBatchParams) (sqlc.Batch, error)) *MockQuerier_UpdateBatch_Call {
	_c.Call.Return(run)
	return _c
}
