// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocksqlc

import (
	"context"
	"open-fermentations/internal/database/sqlc"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// CreateBatch provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateBatch(ctx context.Context, arg sqlc.CreateBatchParams) (sqlc.Batch, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 sqlc.Batch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateBatchParams) (sqlc.Batch, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateBatchParams) sqlc.Batch); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.Batch)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.CreateBatchParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CreateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatch'
type MockQuerier_CreateBatch_Call struct {
	*mock.Call
}

// CreateBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.CreateBatchParams
func (_e *MockQuerier_Expecter) CreateBatch(ctx any, arg any) *MockQuerier_CreateBatch_Call {
	return &MockQuerier_CreateBatch_Call{Call: _e.mock.On("CreateBatch", ctx, arg)}
}

func (_c *MockQuerier_CreateBatch_Call) Run(run func(ctx context.Context, arg sqlc.CreateBatchParams)) *MockQuerier_CreateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CreateBatchParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CreateBatchParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateBatch_Call) Return(batch sqlc.Batch, err error) *MockQuerier_CreateBatch_Call {
	_c.Call.Return(batch, err)
	return _c
}

func (_c *MockQuerier_CreateBatch_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.CreateBatchParams) (sqlc.Batch, error)) *MockQuerier_CreateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDevice provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateDevice(ctx context.Context, arg sqlc.CreateDeviceParams) (sqlc.Device, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateDevice")
	}

	var r0 sqlc.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateDeviceParams) (sqlc.Device, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateDeviceParams) sqlc.Device); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.Device)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.CreateDeviceParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CreateDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDevice'
type MockQuerier_CreateDevice_Call struct {
	*mock.Call
}

// CreateDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.CreateDeviceParams
func (_e *MockQuerier_Expecter) CreateDevice(ctx any, arg any) *MockQuerier_CreateDevice_Call {
	return &MockQuerier_CreateDevice_Call{Call: _e.mock.On("CreateDevice", ctx, arg)}
}

func (_c *MockQuerier_CreateDevice_Call) Run(run func(ctx context.Context, arg sqlc.CreateDeviceParams)) *MockQuerier_CreateDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CreateDeviceParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CreateDeviceParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateDevice_Call) Return(device sqlc.Device, err error) *MockQuerier_CreateDevice_Call {
	_c.Call.Return(device, err)
	return _c
}

func (_c *MockQuerier_CreateDevice_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.CreateDeviceParams) (sqlc.Device, error)) *MockQuerier_CreateDevice_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateUser(ctx context.Context, arg sqlc.CreateUserParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.CreateUserParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockQuerier_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.CreateUserParams
func (_e *MockQuerier_Expecter) CreateUser(ctx any, arg any) *MockQuerier_CreateUser_Call {
	return &MockQuerier_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, arg)}
}

func (_c *MockQuerier_CreateUser_Call) Run(run func(ctx context.Context, arg sqlc.CreateUserParams)) *MockQuerier_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.CreateUserParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.CreateUserParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateUser_Call) Return(err error) *MockQuerier_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_CreateUser_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.CreateUserParams) error) *MockQuerier_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBatch provides a mock function for the type MockQuerier
func (_mock *MockQuerier) DeleteBatch(ctx context.Context, arg sqlc.DeleteBatchParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.DeleteBatchParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_DeleteBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBatch'
type MockQuerier_DeleteBatch_Call struct {
	*mock.Call
}

// DeleteBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.DeleteBatchParams
func (_e *MockQuerier_Expecter) DeleteBatch(ctx any, arg any) *MockQuerier_DeleteBatch_Call {
	return &MockQuerier_DeleteBatch_Call{Call: _e.mock.On("DeleteBatch", ctx, arg)}
}

func (_c *MockQuerier_DeleteBatch_Call) Run(run func(ctx context.Context, arg sqlc.DeleteBatchParams)) *MockQuerier_DeleteBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.DeleteBatchParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.DeleteBatchParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_DeleteBatch_Call) Return(err error) *MockQuerier_DeleteBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_DeleteBatch_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.DeleteBatchParams) error) *MockQuerier_DeleteBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetBatchById provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetBatchById(ctx context.Context, arg sqlc.GetBatchByIdParams) (sqlc.Batch, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetBatchById")
	}

	var r0 sqlc.Batch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetBatchByIdParams) (sqlc.Batch, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetBatchByIdParams) sqlc.Batch); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.Batch)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetBatchByIdParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetBatchById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBatchById'
type MockQuerier_GetBatchById_Call struct {
	*mock.Call
}

// GetBatchById is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.GetBatchByIdParams
func (_e *MockQuerier_Expecter) GetBatchById(ctx any, arg any) *MockQuerier_GetBatchById_Call {
	return &MockQuerier_GetBatchById_Call{Call: _e.mock.On("GetBatchById", ctx, arg)}
}

func (_c *MockQuerier_GetBatchById_Call) Run(run func(ctx context.Context, arg sqlc.GetBatchByIdParams)) *MockQuerier_GetBatchById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetBatchByIdParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetBatchByIdParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetBatchById_Call) Return(batch sqlc.Batch, err error) *MockQuerier_GetBatchById_Call {
	_c.Call.Return(batch, err)
	return _c
}

func (_c *MockQuerier_GetBatchById_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.GetBatchByIdParams) (sqlc.Batch, error)) *MockQuerier_GetBatchById_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeviceById provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetDeviceById(ctx context.Context, arg sqlc.GetDeviceByIdParams) (sqlc.Device, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetDeviceById")
	}

	var r0 sqlc.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetDeviceByIdParams) (sqlc.Device, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.GetDeviceByIdParams) sqlc.Device); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.Device)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.GetDeviceByIdParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetDeviceById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeviceById'
type MockQuerier_GetDeviceById_Call struct {
	*mock.Call
}

// GetDeviceById is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.GetDeviceByIdParams
func (_e *MockQuerier_Expecter) GetDeviceById(ctx any, arg any) *MockQuerier_GetDeviceById_Call {
	return &MockQuerier_GetDeviceById_Call{Call: _e.mock.On("GetDeviceById", ctx, arg)}
}

func (_c *MockQuerier_GetDeviceById_Call) Run(run func(ctx context.Context, arg sqlc.GetDeviceByIdParams)) *MockQuerier_GetDeviceById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.GetDeviceByIdParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.GetDeviceByIdParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetDeviceById_Call) Return(device sqlc.Device, err error) *MockQuerier_GetDeviceById_Call {
	_c.Call.Return(device, err)
	return _c
}

func (_c *MockQuerier_GetDeviceById_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.GetDeviceByIdParams) (sqlc.Device, error)) *MockQuerier_GetDeviceById_Call {
	_c.Call.Return(run)
	return _c
}

// GetPermissions provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetPermissions(ctx context.Context) ([]sqlc.Permission, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissions")
	}

	var r0 []sqlc.Permission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]sqlc.Permission, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []sqlc.Permission); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.Permission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissions'
type MockQuerier_GetPermissions_Call struct {
	*mock.Call
}

// GetPermissions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuerier_Expecter) GetPermissions(ctx any) *MockQuerier_GetPermissions_Call {
	return &MockQuerier_GetPermissions_Call{Call: _e.mock.On("GetPermissions", ctx)}
}

func (_c *MockQuerier_GetPermissions_Call) Run(run func(ctx context.Context)) *MockQuerier_GetPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQuerier_GetPermissions_Call) Return(permissions []sqlc.Permission, err error) *MockQuerier_GetPermissions_Call {
	_c.Call.Return(permissions, err)
	return _c
}

func (_c *MockQuerier_GetPermissions_Call) RunAndReturn(run func(ctx context.Context) ([]sqlc.Permission, error)) *MockQuerier_GetPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// GetRolesWithPermissions provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetRolesWithPermissions(ctx context.Context) ([]sqlc.GetRolesWithPermissionsRow, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRolesWithPermissions")
	}

	var r0 []sqlc.GetRolesWithPermissionsRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]sqlc.GetRolesWithPermissionsRow, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []sqlc.GetRolesWithPermissionsRow); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.GetRolesWithPermissionsRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetRolesWithPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRolesWithPermissions'
type MockQuerier_GetRolesWithPermissions_Call struct {
	*mock.Call
}

// GetRolesWithPermissions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuerier_Expecter) GetRolesWithPermissions(ctx any) *MockQuerier_GetRolesWithPermissions_Call {
	return &MockQuerier_GetRolesWithPermissions_Call{Call: _e.mock.On("GetRolesWithPermissions", ctx)}
}

func (_c *MockQuerier_GetRolesWithPermissions_Call) Run(run func(ctx context.Context)) *MockQuerier_GetRolesWithPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQuerier_GetRolesWithPermissions_Call) Return(getRolesWithPermissionsRows []sqlc.GetRolesWithPermissionsRow, err error) *MockQuerier_GetRolesWithPermissions_Call {
	_c.Call.Return(getRolesWithPermissionsRows, err)
	return _c
}

func (_c *MockQuerier_GetRolesWithPermissions_Call) RunAndReturn(run func(ctx context.Context) ([]sqlc.GetRolesWithPermissionsRow, error)) *MockQuerier_GetRolesWithPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserById provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetUserById(ctx context.Context, id uuid.UUID) (sqlc.GetUserByIdRow, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserById")
	}

	var r0 sqlc.GetUserByIdRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (sqlc.GetUserByIdRow, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) sqlc.GetUserByIdRow); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlc.GetUserByIdRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetUserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserById'
type MockQuerier_GetUserById_Call struct {
	*mock.Call
}

// GetUserById is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockQuerier_Expecter) GetUserById(ctx any, id any) *MockQuerier_GetUserById_Call {
	return &MockQuerier_GetUserById_Call{Call: _e.mock.On("GetUserById", ctx, id)}
}

func (_c *MockQuerier_GetUserById_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockQuerier_GetUserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetUserById_Call) Return(getUserByIdRow sqlc.GetUserByIdRow, err error) *MockQuerier_GetUserById_Call {
	_c.Call.Return(getUserByIdRow, err)
	return _c
}

func (_c *MockQuerier_GetUserById_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (sqlc.GetUserByIdRow, error)) *MockQuerier_GetUserById_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUsername provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetUserByUsername(ctx context.Context, username string) (sqlc.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 sqlc.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (sqlc.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) sqlc.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(sqlc.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsername'
type MockQuerier_GetUserByUsername_Call struct {
	*mock.Call
}

// GetUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockQuerier_Expecter) GetUserByUsername(ctx any, username any) *MockQuerier_GetUserByUsername_Call {
	return &MockQuerier_GetUserByUsername_Call{Call: _e.mock.On("GetUserByUsername", ctx, username)}
}

func (_c *MockQuerier_GetUserByUsername_Call) Run(run func(ctx context.Context, username string)) *MockQuerier_GetUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetUserByUsername_Call) Return(user sqlc.User, err error) *MockQuerier_GetUserByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockQuerier_GetUserByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (sqlc.User, error)) *MockQuerier_GetUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUsernameWithPasswordAndRolesAndPermissions provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetUserByUsernameWithPasswordAndRolesAndPermissions(ctx context.Context, username string) ([]sqlc.GetUserByUsernameWithPasswordAndRolesAndPermissionsRow, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsernameWithPasswordAndRolesAndPermissions")
	}

	var r0 []sqlc.GetUserByUsernameWithPasswordAndRolesAndPermissionsRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]sqlc.GetUserByUsernameWithPasswordAndRolesAndPermissionsRow, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []sqlc.GetUserByUsernameWithPasswordAndRolesAndPermissionsRow); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.GetUserByUsernameWithPasswordAndRolesAndPermissionsRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetUserByUsernameWithPasswordAndRolesAndPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsernameWithPasswordAndRolesAndPermissions'
type MockQuerier_GetUserByUsernameWithPasswordAndRolesAndPermissions_Call struct {
	*mock.Call
}

// GetUserByUsernameWithPasswordAndRolesAndPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockQuerier_Expecter) GetUserByUsernameWithPasswordAndRolesAndPermissions(ctx any, username any) *MockQuerier_GetUserByUsernameWithPasswordAndRolesAndPermissions_Call {
	return &MockQuerier_GetUserByUsernameWithPasswordAndRolesAndPermissions_Call{Call: _e.mock.On("GetUserByUsernameWithPasswordAndRolesAndPermissions", ctx, username)}
}

func (_c *MockQuerier_GetUserByUsernameWithPasswordAndRolesAndPermissions_Call) Run(run func(ctx context.Context, username string)) *MockQuerier_GetUserByUsernameWithPasswordAndRolesAndPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetUserByUsernameWithPasswordAndRolesAndPermissions_Call) Return(getUserByUsernameWithPasswordAndRolesAndPermissionsRows []sqlc.GetUserByUsernameWithPasswordAndRolesAndPermissionsRow, err error) *MockQuerier_GetUserByUsernameWithPasswordAndRolesAndPermissions_Call {
	_c.Call.Return(getUserByUsernameWithPasswordAndRolesAndPermissionsRows, err)
	return _c
}

func (_c *MockQuerier_GetUserByUsernameWithPasswordAndRolesAndPermissions_Call) RunAndReturn(run func(ctx context.Context, username string) ([]sqlc.GetUserByUsernameWithPasswordAndRolesAndPermissionsRow, error)) *MockQuerier_GetUserByUsernameWithPasswordAndRolesAndPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveDeviceById provides a mock function for the type MockQuerier
func (_mock *MockQuerier) RemoveDeviceById(ctx context.Context, arg sqlc.RemoveDeviceByIdParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for RemoveDeviceById")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.RemoveDeviceByIdParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_RemoveDeviceById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveDeviceById'
type MockQuerier_RemoveDeviceById_Call struct {
	*mock.Call
}

// RemoveDeviceById is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.RemoveDeviceByIdParams
func (_e *MockQuerier_Expecter) RemoveDeviceById(ctx any, arg any) *MockQuerier_RemoveDeviceById_Call {
	return &MockQuerier_RemoveDeviceById_Call{Call: _e.mock.On("RemoveDeviceById", ctx, arg)}
}

func (_c *MockQuerier_RemoveDeviceById_Call) Run(run func(ctx context.Context, arg sqlc.RemoveDeviceByIdParams)) *MockQuerier_RemoveDeviceById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.RemoveDeviceByIdParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.RemoveDeviceByIdParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_RemoveDeviceById_Call) Return(err error) *MockQuerier_RemoveDeviceById_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_RemoveDeviceById_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.RemoveDeviceByIdParams) error) *MockQuerier_RemoveDeviceById_Call {
	_c.Call.Return(run)
	return _c
}

// SearchBatches provides a mock function for the type MockQuerier
func (_mock *MockQuerier) SearchBatches(ctx context.Context, arg sqlc.SearchBatchesParams) ([]sqlc.SearchBatchesRow, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for SearchBatches")
	}

	var r0 []sqlc.SearchBatchesRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.SearchBatchesParams) ([]sqlc.SearchBatchesRow, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.SearchBatchesParams) []sqlc.SearchBatchesRow); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.SearchBatchesRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.SearchBatchesParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_SearchBatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchBatches'
type MockQuerier_SearchBatches_Call struct {
	*mock.Call
}

// SearchBatches is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.SearchBatchesParams
func (_e *MockQuerier_Expecter) SearchBatches(ctx any, arg any) *MockQuerier_SearchBatches_Call {
	return &MockQuerier_SearchBatches_Call{Call: _e.mock.On("SearchBatches", ctx, arg)}
}

func (_c *MockQuerier_SearchBatches_Call) Run(run func(ctx context.Context, arg sqlc.SearchBatchesParams)) *MockQuerier_SearchBatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.SearchBatchesParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.SearchBatchesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_SearchBatches_Call) Return(searchBatchesRows []sqlc.SearchBatchesRow, err error) *MockQuerier_SearchBatches_Call {
	_c.Call.Return(searchBatchesRows, err)
	return _c
}

func (_c *MockQuerier_SearchBatches_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.SearchBatchesParams) ([]sqlc.SearchBatchesRow, error)) *MockQuerier_SearchBatches_Call {
	_c.Call.Return(run)
	return _c
}

// SearchDevices provides a mock function for the type MockQuerier
func (_mock *MockQuerier) SearchDevices(ctx context.Context, arg sqlc.SearchDevicesParams) ([]sqlc.SearchDevicesRow, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for SearchDevices")
	}

	var r0 []sqlc.SearchDevicesRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.SearchDevicesParams) ([]sqlc.SearchDevicesRow, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.SearchDevicesParams) []sqlc.SearchDevicesRow); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.SearchDevicesRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.SearchDevicesParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_SearchDevices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchDevices'
type MockQuerier_SearchDevices_Call struct {
	*mock.Call
}

// SearchDevices is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.SearchDevicesParams
func (_e *MockQuerier_Expecter) SearchDevices(ctx any, arg any) *MockQuerier_SearchDevices_Call {
	return &MockQuerier_SearchDevices_Call{Call: _e.mock.On("SearchDevices", ctx, arg)}
}

func (_c *MockQuerier_SearchDevices_Call) Run(run func(ctx context.Context, arg sqlc.SearchDevicesParams)) *MockQuerier_SearchDevices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.SearchDevicesParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.SearchDevicesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_SearchDevices_Call) Return(searchDevicesRows []sqlc.SearchDevicesRow, err error) *MockQuerier_SearchDevices_Call {
	_c.Call.Return(searchDevicesRows, err)
	return _c
}

func (_c *MockQuerier_SearchDevices_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.SearchDevicesParams) ([]sqlc.SearchDevicesRow, error)) *MockQuerier_SearchDevices_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBatch provides a mock function for the type MockQuerier
func (_mock *MockQuerier) UpdateBatch(ctx context.Context, arg sqlc.UpdateBatchParams) (sqlc.Batch, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBatch")
	}

	var r0 sqlc.Batch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateBatchParams) (sqlc.Batch, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateBatchParams) sqlc.Batch); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.Batch)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.UpdateBatchParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_UpdateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBatch'
type MockQuerier_UpdateBatch_Call struct {
	*mock.Call
}

// UpdateBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.UpdateBatchParams
func (_e *MockQuerier_Expecter) UpdateBatch(ctx any, arg any) *MockQuerier_UpdateBatch_Call {
	return &MockQuerier_UpdateBatch_Call{Call: _e.mock.On("UpdateBatch", ctx, arg)}
}

func (_c *MockQuerier_UpdateBatch_Call) Run(run func(ctx context.Context, arg sqlc.UpdateBatchParams)) *MockQuerier_UpdateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.UpdateBatchParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.UpdateBatchParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_UpdateBatch_Call) Return(batch sqlc.Batch, err error) *MockQuerier_UpdateBatch_Call {
	_c.Call.Return(batch, err)
	return _c
}

func (_c *MockQuerier_UpdateBatch_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.UpdateBatchParams) (sqlc.Batch, error)) *MockQuerier_UpdateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDevice provides a mock function for the type MockQuerier
func (_mock *MockQuerier) UpdateDevice(ctx context.Context, arg sqlc.UpdateDeviceParams) (sqlc.Device, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDevice")
	}

	var r0 sqlc.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateDeviceParams) (sqlc.Device, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sqlc.UpdateDeviceParams) sqlc.Device); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.Device)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sqlc.UpdateDeviceParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_UpdateDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDevice'
type MockQuerier_UpdateDevice_Call struct {
	*mock.Call
}

// UpdateDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlc.UpdateDeviceParams
func (_e *MockQuerier_Expecter) UpdateDevice(ctx any, arg any) *MockQuerier_UpdateDevice_Call {
	return &MockQuerier_UpdateDevice_Call{Call: _e.mock.On("UpdateDevice", ctx, arg)}
}

func (_c *MockQuerier_UpdateDevice_Call) Run(run func(ctx context.Context, arg sqlc.UpdateDeviceParams)) *MockQuerier_UpdateDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 sqlc.UpdateDeviceParams
		if args[1] != nil {
			arg1 = args[1].(sqlc.UpdateDeviceParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_UpdateDevice_Call) Return(device sqlc.Device, err error) *MockQuerier_UpdateDevice_Call {
	_c.Call.Return(device, err)
	return _c
}

func (_c *MockQuerier_UpdateDevice_Call) RunAndReturn(run func(ctx context.Context, arg sqlc.UpdateDeviceParams) (sqlc.Device, error)) *MockQuerier_UpdateDevice_Call {
	_c.Call.Return(run)
	return _c
}
